version: '3.8'
services:

  mysql:
    image: mysql:latest
    container_name: mysql-soda-test
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: testpwd
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: testpwd

  redis:
    image: 'redis:4-alpine'
    container_name: redis-soda-test
    command: redis-server --requirepass testpwd
    ports:
      - '6379:6379'

  postgres:
    image: postgres:latest
    container_name: postgres-soda-test
    environment:
      POSTGRES_USER: thetest
      POSTGRES_PASSWORD: testpwd
      POSTGRES_DB: test
    ports:
      - 5432:5432

  mongo:
    image: mongo:latest
    container_name: mongo-soda-test
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd
      MONGO_INITDB_DATABASE: soda
    ports:
      - 8081:8081