version: '3.8'
services:

  mysql:
    image: mysql:latest
    container_name: mysql-soda-test
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: testpwd
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: testpwd

  redis:
    image: 'redis:4-alpine'
    command: redis-server --requirepass testpwd
    ports:
      - '6379:6379'
