name: Build Soda

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Set up dependencies
      run: docker-compose -f docker-compose-testsuite.yaml up -d --no-recreate
    - name: Check mysql instance
      run: echo "mysql container: $(docker ps -a -q --filter name=mysql-soda-test)"
    - name: Set up mock data
      run: ./init-test-dependencies.sh
    - name: Run tests
      run: sbt test
    - name: Tear down
      run: ./stop-test-dependencies.sh
